- set_fact:
    ansible_hostname: "{{ forge_name }}"
    ansible_fqdn: "{{ forge_name }}.hosts.forgeservicelab.fi"
- debug: msg="fqdn is {{ ansible_fqdn }}"
- debug: msg="hostname is {{ ansible_hostname }}"
- debug: msg="passed stuff is is {{ forge_name }}"
- hostname: name="{{ ansible_fqdn }}"
